# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "cmms-terraform-state-bucket"
    key            = "./terraform.tfstate"
    region         = "us-west-2"
    encrypt        = true
    dynamodb_table = "cmms-terraform-state-table"
  }
}
